export enum OverheadCategory {
  RENT = 'RENT',
  UTILITIES = 'UTILITIES',
  INTERNET = 'INTERNET',
  SOFTWARE_LICENSES = 'SOFTWARE_LICENSES',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  MARKETING = 'MARKETING',
  TRAINING = 'TRAINING',
  INSURANCE = 'INSURANCE',
  LEGAL = 'LEGAL',
  OTHER = 'OTHER',
}
